### ISSUE TITLE
Typo in package.json of seneca-promisified-core?

### ISSUE THREAD

**Issue by timeyr** [AGhost-7/seneca-promisified#1]
Shouldn't `"main": "seneca.js",` be `"main": "index.js",`?

I could only get it to work by making this change.

**Comment by AGhost-7** [comment]
Odd that it was never spotted in the tests. I'll look into it today.

**Comment by AGhost-7** [comment]
Should be fixed, feel free to reopen if that's not the case. Thanks for reporting.
