### ISSUE TITLE
Wrapped entity data$ method always returns undefined

### ISSUE THREAD

**Issue by rixo** [AGhost-7/seneca-promisified#3]
Hi, and thanks for wrapping!

I think I've found a glitch:

    const seneca = new SenecaPromisified(this);
    const ent = seneca.make('example');
    ent.data$({foo: 'bar'}); // this works
    console.log( ent.$data(false) || ent.data$() ); // but this returns undefined

I think [this function](https://github.com/AGhost-7/seneca-promisified/blob/master/packages/seneca-promisified-entity/src/index.js#L155) should return.

**Comment by AGhost-7** [comment]
Doh, should add a return statement. I'll try to fix it tomorrow.

**Comment by rixo** [comment]
Thanks! Unfortunately, a simple return may not be enough because, when used as a setter, `data$` returns the entity. I'd prefer to get the wrapped entity...

    wrappedEnt
      .data$({})
      .save$()
      .then // undefined

**Comment by AGhost-7** [comment]
I noticed you forked -  do you have the intention of fixing this instead?

**Comment by rixo** [comment]
Hmm. Actually I was beginning to wonder if this approach will play well
with the myriad of Seneca plugins, and if I shouldn't learn to love
callback style instead... Do you have any experience with this? Or plans
maybe?

But yeah, I'd be glad to help. I've found other such small
inconsistencies... Do you prefer that I open an issue for each, or I open
pull requests and we discuss them there directly?

**Comment by AGhost-7** [comment]
It looks like they've added some new API to Seneca - I don't remember there being any `client` method for example. I think this is mostly going to be about updating the modules here (as well as fixing bugs). Aside from the entity plugin most of the standard plugins are meant to be used through the `act` method. If you're trying to avoid using callbacks I think this still does a decent job.

I'm open for anything as long as I get some tests along with the changes. I'm going to fix the bug you've already brought up in this issue though.

ps. Maybe we could look into finding all of the calls to this method to get a better idea of how much work is involved: https://github.com/senecajs/seneca-entity/blob/master/entity.js#L44

That seems to be what patches seneca to add new methods.

**Comment by AGhost-7** [comment]
Closing this issue since its been fixed. A release has been made and the fixes can now be found on the NPM site.

Thanks for reporting!
